module.exports = {
  metadata: {
    total_objects: 1,
  },
  response: [
    {
      activated: true,
      capabilities: ["auto", "push", "sms", "mobile_otp"],
      encrypted: "Encrypted",
      extension: "",
      fingerprint: "Configured",
      last_seen: "2022-02-17T16:42:38",
      model: "Google Pixel 5",
      name: "",
      number: "+15555555555",
      phone_id: "DPB9DRDAI6PONK6CVHKC",
      platform: "Google Android",
      screenlock: "Locked",
      sms_passcodes_sent: false,
      tampered: "Not tampered",
      type: "Mobile",
      users: [
        {
          alias1: null,
          alias2: null,
          alias3: null,
          alias4: null,
          aliases: {},
          created: 1644967413,
          email: "austin.kelleher+duotest@jupiterone.com",
          firstname: null,
          is_enrolled: false,
          last_directory_sync: null,
          last_login: null,
          lastname: null,
          notes: "Hello notes!",
          realname: "Austin Kelleher Test",
          status: "active",
          user_id: "DUNWSZS0P50553CA4FAH",
          username: "austinkellehertest",
        },
      ],
    },
  ],
  stat: "OK",
};
