module.exports = {
  metadata: {
    total_objects: 1,
  },
  response: [
    {
      alias1: null,
      alias2: null,
      alias3: null,
      alias4: null,
      aliases: {},
      created: 1644967413,
      desktoptokens: [],
      email: "austin.kelleher+duotest@jupiterone.com",
      firstname: null,
      groups: [
        {
          desc: "test group",
          group_id: "DGYM32D735SEKRC8X7S5",
          mobile_otp_enabled: false,
          name: "testJ1Group",
          push_enabled: false,
          sms_enabled: false,
          status: "Bypass",
        },
      ],
      is_enrolled: true,
      last_directory_sync: null,
      last_login: null,
      lastname: null,
      notes: "Hello notes!",
      phones: [
        {
          activated: true,
          capabilities: ["auto", "push", "sms", "mobile_otp"],
          encrypted: "Encrypted",
          extension: "",
          fingerprint: "Configured",
          last_seen: "2022-02-17T16:42:38",
          model: "Google Pixel 5",
          name: "",
          number: "+15555555555",
          phone_id: "DPB9DRDAI6PONK6CVHKC",
          platform: "Google Android",
          screenlock: "Locked",
          sms_passcodes_sent: false,
          tampered: "Not tampered",
          type: "Mobile",
        },
      ],
      realname: "Austin Kelleher Test",
      status: "active",
      tokens: [],
      u2ftokens: [],
      user_id: "DUNWSZS0P50553CA4FAH",
      username: "austinkellehertest",
      webauthncredentials: [],
    },
  ],
  stat: "OK",
};
