module.exports = {
  response: {
    enrollment_module: "new",
    fraud_email: "",
    fraud_email_enabled: true,
    helpdesk_bypass: "allow",
    helpdesk_bypass_expiration: 0,
    helpdesk_can_send_enroll_email: false,
    helpdesk_message: "",
    inactive_admin_expiration: 0,
    inactive_user_expiration: 0,
    instant_restore_enabled: 1,
    language: "EN",
    lockout_expire_duration: null,
    lockout_threshold: 10,
    log_retention_days: null,
    minimum_password_length: 12,
    mobile_analytics_disabled: 0,
    mobile_otp_enabled: false,
    name: "JupiterOne Inc",
    password_requires_lower_alpha: false,
    password_requires_numeric: false,
    password_requires_special: false,
    password_requires_upper_alpha: false,
    push_enabled: false,
    reactivation_integration_key: null,
    reactivation_url: "",
    req_fips_passcodes_android: false,
    security_checkup_enabled: 1,
    sms_batch: 1,
    sms_enabled: false,
    sms_expiration: 0,
    sms_message: "SMS passcodes",
    sms_refresh: 0,
    telephony_warning_min: 0,
    timezone: "UTC",
    user_telephony_cost_max: 20,
  },
  stat: "OK",
};
